version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - SOURCE_VERSION=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - pip3 install --upgrade pip -t lib
      - pip3 install --upgrade awscli -t lib
      - pip3 install -Iv aws-sam-cli==1.19.1 -t lib
      - pip3 install pylint -t lib
      - pip3 install pyspark -t lib
      - pip3 install moto -t lib
      - pip3 install pandas -t lib
      - pip3 install pytest -t lib
      - pip3 install pytest-cov -t lib
      - pip3 install tabulate -t lib
      - pip3 install psycopg2 -t lib
  pre_build:
    commands:
      - echo "Zipping the packages"
      - cd lib
      - zip -r9 ../deployment_package.zip
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uopdating   lambda"
      - aws lambda update-function-code --function-name test_function --zip-file fileb://deployment_package.zip
      - echo "Done"
